front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

medecin:
    path:     /doctors
    defaults: { _controller: FrontBundle:Default:Medecin }

medecin_profile:
    path:     /doctors/profile/show
    defaults: { _controller: FrontBundle:Default:MedecinHome }

medecin_rdv:
    path:     /doctors/profile/rdv
    defaults: { _controller: UserBundle:RDV:RDV}

medecin_rechehrche:
    path:     /doctors/recherche
    defaults: { _controller: FrontBundle:Default:rechercher }


pdf_rdv:
    path:     /rdv/fiche
    defaults: { _controller: FrontBundle:Default:pdfRDV }

profile_user:
    path:     /user/profile
    defaults: { _controller: FrontBundle:Default:profile }

profile_medecin:
    path:     /doctors/profile
    defaults: { _controller: FrontBundle:Default:profilemed }

update_rdv:
    path:     /rdv/update
    defaults: { _controller: FrontBundle:Default:updaterdv }
valider_rdv:
    path:     /rdv/valider
    defaults: { _controller: FrontBundle:Default:validerrdv }
annuler_rdv:
    path:     /rdv/anuuler
    defaults: { _controller: FrontBundle:Default:annulerrdv }

annuler_rdv_user:
    path:     /rdv/anuuler
    defaults: { _controller: FrontBundle:Default:annulerrdvuser }

medecin_rechercher_spec:
    path:     /doctors/recherche/spec
    defaults: { _controller: FrontBundle:Default:rechercherSpec }

delete_rdv_user:
    path:     /rdv/delete
    defaults: { _controller: FrontBundle:Default:DeleteRdv }