facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

custom_login:
    path: /login/check-custom

github_login:
    path: /login/check-github
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /auth/login
user_medecin:
    resource: "@UserBundle/Controller/MedecinController.php"
    type:     annotation

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evenement
medicament:
    resource: "@MedicamentBundle/Resources/config/routing.yml"
    prefix:   /medicament

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /shop