services:
  # [...] Vos autres services
  redirect.after.login:
    class: UserBundle\Redirection\AfterLoginRedirection
    arguments: ["@router"]

#my.oauth_aware.user_provider.service:
#    class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
#    arguments:
#        - '@fos_user.user_manager'
#        - ['pass properties as array']