<?php

namespace UserBundle\Repository;

/**
 * RDVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RDVRepository extends \Doctrine\ORM\EntityRepository
{
    function RDVdql($id){
        $qb=$this->getEntityManager()
            ->createQuery("SELECT m FROM UserBundle:RDV m WHERE m.medecin=:med")
            ->setParameter('med','%'.$id.'%');
        return $qb->getResult();
    }
}
