<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindBydescriptiondql($titre){

        $qd=$this->getEntityManager()->createQuery("select m from EvenementBundle:Evenement m where m.titre like :titre ")
            ->setParameter('titre',$titre);
        return $qd->getResult();

    }






}
