<?php

namespace AnnonceBundle\Repository;

/**
 * annonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class annonceRepository extends \Doctrine\ORM\EntityRepository
{



    public function FindBydescriptiondql($titre){

        $qd=$this->getEntityManager()->createQuery("select m from AnnonceBundle:Annonce m where m.titre like :titre ")
            ->setParameter('titre',$titre);
        return $qd->getResult();

    }


    public function afficheAnnonceValides()
    {
        $qd = $this->getEntityManager()
            ->createQuery("SELECT annonce FROM AnnonceBundle:Annonce annonce WHERE annonce.confirmation like :confirmation")
            ->setParameter('confirmation', '%0%');
        return $qd->getResult();

    }

    public function validerannonceAction($id)
    {

        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('AnnonceBundle:Annonce', 'p')
            ->set('p.confirmation', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, '0')
            ->setParameter(2, $id);

        return $qB->getQuery();

    }


    public function bloqueannonceActionn($id)
    {

        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB ->update('AnnonceBundle:Annonce', 'p')
            ->set('p.confirmation', '?1')
            ->where('p.id = ?2')
            ->setParameter(1, '1')
            ->setParameter(2, $id);

        return $qB->getQuery();



    }

}
